import {test,expect} from '@playwright/test';
import {appendAITodos,executeSomaActions,parseSomaActions,type AIActionStore} from '../src/lib/aiActions';
import type {Todo,Subject,TodoSession} from '../src/types';
function setup(){const state={todos:[{id:'existing',text:'Keep my original task',date:'2026-01-01',status:'nothing'}] as Todo[],subjects:[{id:'biology',name:'Biology',color:'#66bb6a',totalTimeToday:0}] as Subject[],sessions:[] as TodoSession[],failTask:false,failSession:false,failDelete:false,events:[] as string[]};const store:AIActionStore={getTodos:()=>state.todos,getSubjects:()=>state.subjects,fetchAllTodos:async()=>state.todos,fetchSubjects:async()=>state.subjects,saveTodo:async t=>{state.events.push('save-task');if(state.failTask)throw new Error('task save failed');state.todos=[...state.todos.filter(x=>x.id!==t.id),t];},deleteTodo:async id=>{if(state.failDelete)throw new Error('delete failed');state.todos=state.todos.filter(t=>t.id!==id);},saveSubject:async s=>{state.subjects=[...state.subjects.filter(x=>x.id!==s.id),s];},deleteSubject:async id=>{state.subjects=state.subjects.filter(s=>s.id!==id);},saveTodoSession:async s=>{state.events.push('save-session');if(!state.todos.some(t=>t.id===s.todoId))throw new Error('missing parent');if(state.failSession)throw new Error('session failed');const id=crypto.randomUUID();state.sessions.push({...s,id});return id;},fetchTodoSessionsByTodoId:async id=>state.sessions.filter(s=>s.todoId===id),fetchTodoSessionById:async id=>{const found=state.sessions.find(s=>s.id===id);if(!found)throw new Error('not found');return found;},deleteTodoSession:async id=>{state.sessions=state.sessions.filter(s=>s.id!==id);},updateTodoSession:async(id,patch)=>{state.sessions=state.sessions.map(s=>s.id===id?{...s,...patch}:s);}};return {state,store};}
const session={date:'2027-01-01',start_time:'2027-01-01T10:00:00',end_time:'2027-01-01T10:30:00'};
test('accepting todos appends without deleting existing tasks and safely retries',async()=>{const {state,store}=setup();const items=[{text:'New task',subjectId:'biology'}];await appendAITodos(items,store);await appendAITodos(items,store);expect(state.todos.map(t=>t.text)).toEqual(['Keep my original task','New task']);});
test('parent task is saved before its sessions and duplicate blocks are reused',async()=>{const {state,store}=setup();const actions=[{action:'create_todo' as const,title:'Biology study',subject_id:'biology',sessions:[session,session]}];await executeSomaActions(actions,store);expect(state.events).toEqual(['save-task','save-session']);expect(state.sessions).toHaveLength(1);await executeSomaActions(actions,store);expect(state.sessions).toHaveLength(1);expect(state.todos).toHaveLength(2);});
test('a failed task save prevents session writes and stops the remaining batch',async()=>{const {state,store}=setup();state.failTask=true;const result=await executeSomaActions([{action:'create_todo',title:'Study',sessions:[session]},{action:'delete_todo',todo_id:'existing'}],store);expect(result.join()).toContain('Remaining changes were not applied');expect(state.events).toEqual(['save-task']);expect(state.todos).toHaveLength(1);});
test('failed scheduling compensates the new task without deleting unrelated tasks',async()=>{const {state,store}=setup();state.failSession=true;const results=await executeSomaActions([{action:'create_todo',title:'Study',sessions:[session]}],store);expect(results.join()).toContain('rolled back');expect(state.todos.map(t=>t.id)).toEqual(['existing']);});
test('delete failure never returns a success confirmation or removes cached data',async()=>{const {state,store}=setup();state.failDelete=true;const results=await executeSomaActions([{action:'delete_todo',todo_id:'existing'}],store);expect(results.join()).toContain('✗');expect(results.join()).not.toContain('✓');expect(state.todos).toHaveLength(1);});
test('invalid time intervals and unknown subjects cannot create tasks',async()=>{const {state,store}=setup();await expect(executeSomaActions([{action:'create_todo',title:'Invalid',sessions:[{...session,end_time:session.start_time}]}],store)).rejects.toThrow('Invalid session times');const result=await executeSomaActions([{action:'create_todo',title:'Unknown',subject_id:'not-mine'}],store);expect(result.join()).toContain('No task was created');expect(state.todos).toHaveLength(1);});
test('schedule validator failure prevents a new plan from being saved',async()=>{const {state,store}=setup();const result=await executeSomaActions([{action:'create_todo',title:'Conflicting',sessions:[session]}],store,async()=>{throw new Error('calendar incomplete');});expect(result.join()).toContain('rolled back');expect(state.sessions).toHaveLength(0);expect(state.todos).toHaveLength(1);});
test('artifact JSON never executes as an action and invalid nested sessions fail closed',()=>{expect(parseSomaActions('<artifact>{"action":"delete_todo","todo_id":"existing"}</artifact>')).toEqual([]);expect(()=>parseSomaActions('<soma-action>{"action":"create_todo","title":"Study","sessions":[{}]}</soma-action>')).toThrow('invalid action');});
